### ISSUE TITLE
Avvio server

### ISSUE THREAD

**Issue by mmaridev** [Scuola247/Desktop#1]
Ho scaricato il repository sul mio server ma non riesco a capire come fare a lanciare il servizio. Per questo progetto non c'è un wiki di riferimento?

**Comment by folstuff** [comment]
Mi scuso se rispondo con un po' di ritardo ma ho voluto fare delle prove per vedere se riuscivo a sistemare i sorgenti ma purtroppo è un lavoro che richiede più tempo del previsto.
La situazione è la seguente:
Il progetto non è ancora completo, le parti finite sono le stampe de registri e il registro del professore (tabellone dei voti) mentre quelle che mancono sono le interfacce web del registro di classe e quelle di servizio (inserimento di scuole, classi ecc..) oltre ad altre cose minori.
Bisogna però tenere conto che i sorgenti caricati in questo momento fanno riferimento al database prima della conversione in inglese, bisogna quindi scaricare i repositori tenendo conto della versione: se si scaricano i sorgenti della versione v0.1.9-alpha anche il database deve essere scaricato con la stessa versione.
Stiamo ovviamente lavorando per far utilizzare il progetto dal prossimo anno scolastico.
